artifact: Chainsaw_LateralMovement
tool: Chainsaw
description: Lateral Movement
discovery:
  filename_patterns:
    - lateral_movement.csv
  foldername_patterns:
    - chainsaw
    - EventLogs
  required_headers:
    - timestamp
    - Event ID
    - Computer
    - Channel
    - detections
    - path
  strict_filename_match: true
  strict_folder_match: false
  strict_header_match: false
enabled: true
