artifact: Chainsaw_DefenseEvasion
tool: Chainsaw
description: Defense Evasion
discovery:
  filename_patterns:
    - defense_evasion.csv
  foldername_patterns:
    - chainsaw
    - EventLogs
  required_headers:
    - timestamp
    - Event ID
    - Computer
    - Channel
    - detections
    - path
  strict_filename_match: true
  strict_folder_match: false
  strict_header_match: false
enabled: true
