artifact: Chainsaw_ServiceTampering
tool: Chainsaw
description: Service Tampering
discovery:
  filename_patterns:
    - service_tampering.csv
  foldername_patterns:
    - chainsaw
    - EventLogs
  required_headers:
    - timestamp
    - Event ID
    - Computer
    - Channel
    - detections
    - path
  strict_filename_match: true
  strict_folder_match: false
  strict_header_match: false
enabled: true
