artifact: Registry
tool: EZ Tools
description: Registry
discovery:
  filename_patterns:
    - RECmd_Batch_Kroll_Batch_Output.csv
    - RECmd_Batch_DFIRBatch_Output.csv
  foldername_patterns:
    - Registry
  required_headers:
    - HivePath
    - HiveType
    - Description
    - Category
    - KeyPath
    - ValueName
    - ValueType
    - ValueData
    - LastWriteTimestamp
  strict_filename_match: false
  strict_folder_match: false
  strict_header_match: false
enabled: true

