artifact: Shellbags
tool: EZ Tools
description: File & Folder Access
discovery:
  filename_patterns:
    - UsrClass.csv
    - NTUSER.csv
  foldername_patterns:
    - FileFolderAccess
  required_headers:
    - BagPath
    - AbsolutePath
    - Value
    - LastWriteTime
    - FirstInteracted
    - LastInteracted
  strict_filename_match: false
  strict_folder_match: false
  strict_header_match: false
enabled: true

